packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"
  - "generated-apps/*"
  - "demo2"

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32
  cpu:
    - current
    - x64
    - arm64
