packages:
  - "apps/*"
  - "packages/*"
  - 'examples/*'
  - 'examples/showcase-suite/apps/*'
  - 'examples/showcase-suite/packages/*'
  - "examples/reference-apps/*"
  - "examples/p10-gauntlet/*"
  - "examples/superapp-command-center/*"
  - "examples/builder-labs/*"
  - "demo2"
  - "labs/*"

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32
  cpu:
    - current
    - x64
    - arm64
