packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"
  - "examples/reference-apps/*"
  - "examples/p10-gauntlet/*"
  - "demo2"
  - "labs/*"

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32
  cpu:
    - current
    - x64
    - arm64
