import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Layout, Card, CardHeader, CardBody, Button, GauntletVisualizer } from '@showcase/shared-ui';
export function App() {
    const [health, setHealth] = useState(null);
    const [wallet, setWallet] = useState(null);
    useEffect(() => {
        fetch('/api/health').then(r => r.json()).then(setHealth).catch(console.error);
        fetch('/api/wallet').then(r => r.json()).then(setWallet).catch(console.error);
    }, []);
    return (_jsxs(Layout, { title: "Mission Control", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(Card, { children: [_jsx(CardHeader, { title: "Node Daemon Status", subtitle: "Sync daemon lifecycle and RPC connectivity" }), _jsxs(CardBody, { children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "Network" }), _jsx("span", { className: "text-emerald-400 font-mono", children: health?.network || '...' })] }), _jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "Daemon Running" }), _jsx("span", { className: "text-emerald-400 font-mono", children: health?.daemon ? 'YES' : 'NO' })] })] }), _jsxs("div", { className: "mt-6 flex space-x-3", children: [_jsx(Button, { variant: "primary", children: "Start Miner" }), _jsx(Button, { variant: "secondary", children: "View Logs" })] })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Treasury Wallet", subtitle: "Localnet Funding & UTXOs" }), _jsxs(CardBody, { children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "Balance" }), _jsxs("span", { className: "text-emerald-400 font-mono text-xl", children: [wallet ? (Number(wallet.totalSompi) / 100000000).toFixed(2) : '...', " KAS"] })] }), _jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "UTXO Count" }), _jsx("span", { className: "text-gray-200 font-mono", children: wallet?.utxoCount || 0 })] })] }), _jsx("div", { className: "mt-6", children: _jsx(Button, { variant: "primary", className: "w-full", children: "Send Funding Transaction" }) })] })] })] }), _jsx("div", { className: "mt-6", children: _jsx(GauntletVisualizer, {}) })] }));
}
