import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Layout, Card, CardHeader, CardBody, GauntletVisualizer } from '@showcase/shared-ui';
export function App() {
    const [stats, setStats] = useState(null);
    const [blocks, setBlocks] = useState([]);
    useEffect(() => {
        fetch('/api/dag/stats').then(r => r.json()).then(setStats).catch(console.error);
        fetch('/api/dag/blocks').then(r => r.json()).then(setBlocks).catch(console.error);
    }, []);
    return (_jsxs(Layout, { title: "Explorer Live", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsx("div", { className: "md:col-span-1 space-y-6", children: _jsxs(Card, { children: [_jsx(CardHeader, { title: "DAG Stats" }), _jsx(CardBody, { children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "Blue Score" }), _jsx("span", { className: "text-blue-400 font-mono font-bold", children: stats?.blueScore || '...' })] }), _jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "Tips" }), _jsx("span", { className: "text-pink-400 font-mono font-bold", children: stats?.tips || '...' })] }), _jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-900 rounded-lg border border-gray-800", children: [_jsx("span", { className: "text-gray-400", children: "Difficulty" }), _jsx("span", { className: "text-yellow-400 font-mono font-bold", children: stats?.difficulty || '...' })] })] }) })] }) }), _jsx("div", { className: "md:col-span-2", children: _jsxs(Card, { children: [_jsx(CardHeader, { title: "Recent Blocks", subtitle: "Live stream of DAG updates" }), _jsx(CardBody, { children: _jsx("div", { className: "space-y-3", children: blocks.length === 0 ? _jsx("p", { children: "No blocks found." }) : blocks.map((b) => (_jsxs("div", { className: "p-3 bg-gray-900 rounded-lg border border-gray-800 flex justify-between items-center hover:border-emerald-500/50 transition-colors cursor-pointer", children: [_jsxs("div", { children: [_jsx("div", { className: "font-mono text-sm text-emerald-400", children: b.hash }), _jsx("div", { className: "text-xs text-gray-500", children: new Date(Number(b.timestamp)).toLocaleTimeString() })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "font-bold text-white", children: ["Score ", b.blueScore] }), _jsxs("div", { className: "text-xs text-gray-400", children: [b.txCount, " TXs"] })] })] }, b.hash))) }) })] }) })] }), _jsx("div", { className: "mt-8", children: _jsx(GauntletVisualizer, {}) })] }));
}
