import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { cliDist, childEnv } from "./first-contact-helpers.js";

vi.setConfig({ testTimeout: 180_000, hookTimeout: 180_000 });

// CONTAINMENT-2 (R1) · a NAME given to a command is one plain path component under the directory the command owns, and
// it is checked before anything is read, written or deleted:
//   - a keystore name (accounts real generate / import / session-open / change-password) under .hardkas/keystore;
//   - a lock name (lock clear) under .hardkas/locks.
// A name that is not one plain segment is refused with a typed usage error and touches nothing, inside or outside the
// workspace. An import whose name is already taken is refused before its keystore is written (the existing account's
// keystore is never replaced). Every probe works inside a temporary directory created here.

const PW_ENV = "HK_CONTAINMENT_PW";
const KEY_ENV = "HK_CONTAINMENT_KEY";
const PASSWORD = "containment-2-password";

interface Run {
  status: number | null;
  stdout: string;
  stderr: string;
  code: string | null;
}

const cli = (args: string[], cwd: string, extraEnv: Record<string, string> = {}): Run => {
  const r = spawnSync(process.execPath, [cliDist, ...args], {
    cwd,
    env: childEnv({ [PW_ENV]: PASSWORD, ...extraEnv }),
    encoding: "utf8",
    input: "",
    timeout: 120_000
  });
  const stdout = r.stdout ?? "";
  const stderr = r.stderr ?? "";
  const code = /"code"\s*:\s*"([A-Z][A-Z0-9_]+)"/.exec(stdout)?.[1] ?? /\[([A-Z][A-Z0-9_]+)\]/.exec(`${stdout}\n${stderr}`)?.[1] ?? null;
  return { status: r.status, stdout, stderr, code };
};

/** A fresh parent with a workspace (`ws`, with its .hardkas) and an `outside` directory next to it. */
const makeParent = (): { parent: string; ws: string; outside: string } => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "hk-containment-2-"));
  const ws = path.join(parent, "ws");
  const outside = path.join(parent, "outside");
  fs.mkdirSync(path.join(ws, ".hardkas"), { recursive: true });
  fs.mkdirSync(outside);
  return { parent, ws, outside };
};

/** Every file under `dir`, relative, sorted (the evidence that nothing else was written). */
const filesUnder = (dir: string): string[] => {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  const walk = (d: string) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else out.push(path.relative(dir, p).split(path.sep).join("/"));
    }
  };
  walk(dir);
  return out.sort();
};

/** Every entry under `dir` with, for a file, the sha256 of its bytes: two equal snapshots mean nothing changed. */
const treeSnapshot = (dir: string): string => {
  const lines: string[] = [];
  const walk = (d: string) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      const rel = path.relative(dir, p).split(path.sep).join("/");
      if (e.isDirectory()) {
        lines.push(`${rel}/`);
        walk(p);
      } else lines.push(`${rel} ${crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")}`);
    }
  };
  walk(dir);
  return lines.sort().join("\n");
};

/** What an account command may have written: keystores, the account store, or a stray `<name>.json` in .hardkas. */
const writtenAccountFiles = (ws: string): string[] =>
  filesUnder(path.join(ws, ".hardkas")).filter((f) => f.startsWith("keystore/") || f === "accounts.real.json" || /^[^/]+\.json$/.test(f));

const VICTIM = "victim bytes: must never change\n";

describe("CONTAINMENT-2 · keystore names stay one plain segment under .hardkas/keystore", () => {
  const parents: string[] = [];
  let simnetKey: { address: string; privateKey: string };

  beforeAll(() => {
    // A simnet key pair for the import cases, generated by the CLI itself in a scratch workspace (never printed).
    const { parent, ws } = makeParent();
    parents.push(parent);
    const g = cli(["accounts", "real", "generate", "--name", "src", "--unsafe-plaintext", "--yes", "--json"], ws);
    expect(g.status, `${g.stdout}${g.stderr}`).toBe(0);
    const store = JSON.parse(fs.readFileSync(path.join(ws, ".hardkas", "accounts.real.json"), "utf8"));
    simnetKey = { address: store.accounts[0].address, privateKey: store.accounts[0].privateKey };
    expect(simnetKey.privateKey).toMatch(/^[0-9a-f]{64}$/);
  });

  afterAll(() => {
    for (const p of parents) fs.rmSync(p, { recursive: true, force: true });
  });

  it("S2 · generate --name <absolute path>: refused before the write; the outside file is untouched", () => {
    const { parent, ws, outside } = makeParent();
    parents.push(parent);
    const victim = path.join(outside, "victim.json");
    fs.writeFileSync(victim, VICTIM);
    const r = cli(["accounts", "real", "generate", "--name", path.join(outside, "victim"), "--password-env", PW_ENV, "--json"], ws);
    expect({ status: r.status, code: r.code, victim: fs.readFileSync(victim, "utf8"), written: writtenAccountFiles(ws) }, `${r.stdout}${r.stderr}`).toEqual({
      status: 2,
      code: "ACCOUNT_NAME_INVALID",
      victim: VICTIM,
      written: []
    });
  });

  it("S2 · generate --name ../esc: refused before the write; no stray keystore anywhere", () => {
    const { parent, ws } = makeParent();
    parents.push(parent);
    const r = cli(["accounts", "real", "generate", "--name", "../esc", "--password-env", PW_ENV, "--json"], ws);
    // `../esc` resolves to .hardkas/esc.json (counted by writtenAccountFiles); nothing may appear next to the workspace either.
    expect({ status: r.status, code: r.code, written: writtenAccountFiles(ws), besideWorkspace: fs.readdirSync(parent).sort() }, `${r.stdout}${r.stderr}`).toEqual({
      status: 2,
      code: "ACCOUNT_NAME_INVALID",
      written: [],
      besideWorkspace: ["outside", "ws"]
    });
  });

  it("S1 · import --name <absolute path>: refused before the keystore is written; the outside file is untouched", () => {
    const { parent, ws, outside } = makeParent();
    parents.push(parent);
    const victim = path.join(outside, "victim.json");
    fs.writeFileSync(victim, VICTIM);
    const r = cli(
      ["accounts", "real", "import", "--name", path.join(outside, "victim"), "--address", simnetKey.address, "--private-key-env", KEY_ENV, "--password-env", PW_ENV, "--json"],
      ws,
      { [KEY_ENV]: simnetKey.privateKey }
    );
    expect({ status: r.status, code: r.code, victim: fs.readFileSync(victim, "utf8"), written: writtenAccountFiles(ws) }, `${r.stdout}${r.stderr}`).toEqual({
      status: 2,
      code: "ACCOUNT_NAME_INVALID",
      victim: VICTIM,
      written: []
    });
  });

  it("S1 · import over an existing account (same name, any case): refused before the write; the existing keystore is untouched", () => {
    const { parent, ws } = makeParent();
    parents.push(parent);
    const g = cli(["accounts", "real", "generate", "--name", "alice", "--password-env", PW_ENV, "--json"], ws);
    expect(g.status, `${g.stdout}${g.stderr}`).toBe(0);
    const keystore = path.join(ws, ".hardkas", "keystore", "alice.json");
    const before = fs.readFileSync(keystore);
    const storeBefore = fs.readFileSync(path.join(ws, ".hardkas", "accounts.real.json"));
    const results = ["alice", "Alice"].map((name) => {
      const r = cli(
        ["accounts", "real", "import", "--name", name, "--address", simnetKey.address, "--private-key-env", KEY_ENV, "--password-env", PW_ENV, "--json"],
        ws,
        { [KEY_ENV]: simnetKey.privateKey }
      );
      return {
        name,
        status: r.status,
        code: r.code,
        keystoreUnchanged: fs.readFileSync(keystore).equals(before),
        storeUnchanged: fs.readFileSync(path.join(ws, ".hardkas", "accounts.real.json")).equals(storeBefore),
        keystores: filesUnder(path.join(ws, ".hardkas", "keystore"))
      };
    });
    expect(results).toEqual(
      ["alice", "Alice"].map((name) => ({ name, status: 2, code: "ACCOUNT_NAME_TAKEN", keystoreUnchanged: true, storeUnchanged: true, keystores: ["alice.json"] }))
    );
  });

  it("S4 · session-open <absolute path>: refused before anything is read (a keystore outside the workspace is never opened)", () => {
    const { parent, ws, outside } = makeParent();
    parents.push(parent);
    // A real encrypted keystore, in another workspace.
    const other = path.join(outside, "other-ws");
    fs.mkdirSync(path.join(other, ".hardkas"), { recursive: true });
    const g = cli(["accounts", "real", "generate", "--name", "outsider", "--password-env", PW_ENV, "--json"], other);
    expect(g.status, `${g.stdout}${g.stderr}`).toBe(0);
    const r = cli(["accounts", "real", "session-open", path.join(other, ".hardkas", "keystore", "outsider"), "--password-env", PW_ENV], ws);
    expect({ status: r.status, code: r.code, verified: /verified/i.test(r.stdout + r.stderr) }, `${r.stdout}${r.stderr}`).toEqual({
      status: 2,
      code: "ACCOUNT_NAME_INVALID",
      verified: false
    });
  });

  it("S3 · change-password <absolute path>: refused before anything is read or prompted for; the outside file is untouched", () => {
    const { parent, ws, outside } = makeParent();
    parents.push(parent);
    const victim = path.join(outside, "victim.json");
    fs.writeFileSync(victim, VICTIM);
    const r = cli(["accounts", "real", "change-password", path.join(outside, "victim")], ws);
    expect({ status: r.status, code: r.code, victim: fs.readFileSync(victim, "utf8") }, `${r.stdout}${r.stderr}`).toEqual({
      status: 2,
      code: "ACCOUNT_NAME_INVALID",
      victim: VICTIM
    });
  });

  it("R1-I1 · every refused name has zero side effects: the workspace and what surrounds it stay byte-identical", () => {
    const { parent, ws, outside } = makeParent();
    parents.push(parent);
    // the lock machinery's own directory exists up front, so ANY created entry is a side effect of the refused name
    fs.mkdirSync(path.join(ws, ".hardkas", "locks"), { recursive: true });
    fs.writeFileSync(path.join(outside, "victim.json"), VICTIM);
    fs.writeFileSync(path.join(ws, "yarn.lock"), "# yarn lockfile v1\n");
    fs.writeFileSync(path.join(parent, "victim.lock"), "not json\n");
    const before = treeSnapshot(parent);
    const victimName = path.join(outside, "victim");
    const runs = [
      ["accounts", "real", "generate", "--name", victimName, "--password-env", PW_ENV, "--json"],
      ["accounts", "real", "generate", "--name", "../esc", "--password-env", PW_ENV, "--json"],
      ["accounts", "real", "generate", "--name", "CON", "--password-env", PW_ENV, "--json"],
      ["accounts", "real", "generate", "--name", "nul", "--unsafe-plaintext", "--yes", "--json"],
      ["accounts", "real", "import", "--name", victimName, "--address", simnetKey.address, "--private-key-env", KEY_ENV, "--password-env", PW_ENV, "--json"],
      ["accounts", "real", "session-open", victimName, "--password-env", PW_ENV],
      ["accounts", "real", "change-password", victimName],
      ["lock", "clear", "../../yarn", "--force"],
      ["lock", "clear", "../../../victim", "--force"],
      ["lock", "clear", "CON", "--force"]
    ].map((args) => {
      const r = cli(args, ws, { [KEY_ENV]: simnetKey.privateKey });
      return { args: args.slice(0, 4).join(" "), status: r.status, code: r.code };
    });
    expect({ runs: runs.map((r) => [r.status, r.code]), unchanged: treeSnapshot(parent) === before }, JSON.stringify(runs, null, 1)).toEqual({
      runs: [
        ...Array(7).fill([2, "ACCOUNT_NAME_INVALID"]),
        ...Array(3).fill([2, "LOCK_NAME_INVALID"])
      ],
      unchanged: true
    });
  });

  it("control: a plain name still generates, opens and is listed", () => {
    const { parent, ws } = makeParent();
    parents.push(parent);
    const g = cli(["accounts", "real", "generate", "--name", "bob", "--password-env", PW_ENV, "--json"], ws);
    expect(g.status, `${g.stdout}${g.stderr}`).toBe(0);
    const o = cli(["accounts", "real", "session-open", "bob", "--password-env", PW_ENV], ws);
    expect({ status: o.status, verified: /verified/i.test(o.stdout + o.stderr), keystores: filesUnder(path.join(ws, ".hardkas", "keystore")) }, `${o.stdout}${o.stderr}`).toEqual({
      status: 0,
      verified: true,
      keystores: ["bob.json"]
    });
  });
});

describe("CONTAINMENT-2 · lock clear <name> only ever touches .hardkas/locks/<name>.lock", () => {
  let parent: string;
  let ws: string;

  beforeAll(() => {
    ({ parent, ws } = makeParent());
  });

  afterAll(() => {
    fs.rmSync(parent, { recursive: true, force: true });
  });

  it("S5 · a name that climbs out of .hardkas/locks is refused; the *.lock files it would reach survive", () => {
    const projectLock = path.join(ws, "yarn.lock");
    const outsideLock = path.join(parent, "victim.lock");
    const results = [
      ["../../yarn", projectLock],
      ["../../../victim", outsideLock],
      [outsideLock.slice(0, -".lock".length), outsideLock]
    ].map(([name, file]) => {
      // each case gets its own target, present before the command runs
      fs.writeFileSync(file!, "not json\n");
      const r = cli(["lock", "clear", name!, "--force"], ws);
      return { name, status: r.status, code: r.code, kept: fs.existsSync(file!) };
    });
    expect(results).toEqual([
      { name: "../../yarn", status: 2, code: "LOCK_NAME_INVALID", kept: true },
      { name: "../../../victim", status: 2, code: "LOCK_NAME_INVALID", kept: true },
      { name: outsideLock.slice(0, -".lock".length), status: 2, code: "LOCK_NAME_INVALID", kept: true }
    ]);
  });

  it("control: a lock under .hardkas/locks is still cleared with --force", () => {
    const locks = path.join(ws, ".hardkas", "locks");
    fs.mkdirSync(locks, { recursive: true });
    fs.writeFileSync(path.join(locks, "accounts.lock"), "corrupt\n");
    const r = cli(["lock", "clear", "accounts", "--force"], ws);
    expect({ status: r.status, exists: fs.existsSync(path.join(locks, "accounts.lock")) }, `${r.stdout}${r.stderr}`).toEqual({ status: 0, exists: false });
  });
});
