packages:
  - "."
allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@hardkas/accounts@0.12.0-rc.16'
  - '@hardkas/artifacts@0.12.0-rc.16'
  - '@hardkas/config@0.12.0-rc.16'
  - '@hardkas/core@0.12.0-rc.16'
  - '@hardkas/jobs@0.12.0-rc.16'
  - '@hardkas/kaspa-rpc@0.12.0-rc.16'
  - '@hardkas/l2@0.12.0-rc.16'
  - '@hardkas/localnet@0.12.0-rc.16'
  - '@hardkas/node-runner@0.12.0-rc.16'
  - '@hardkas/observability@0.12.0-rc.16'
  - '@hardkas/pskt-native@0.12.0-rc.16'
  - '@hardkas/query-store@0.12.0-rc.16'
  - '@hardkas/query@0.12.0-rc.16'
  - '@hardkas/rpc-events@0.12.0-rc.16'
  - '@hardkas/sdk@0.12.0-rc.16'
  - '@hardkas/simulator@0.12.0-rc.16'
  - '@hardkas/toolkit@0.12.0-rc.16'
  - '@hardkas/tx-builder@0.12.0-rc.16'
policies:
  minimumReleaseAge: 0
