import { WalletManagerImpl, WalletStateStoreJson, AddressManager } from '@hardkas/accounts';
import { WalletQuery, WalletQueryProvider } from '@hardkas/query';
import { selectCoins, estimateFee, buildPaymentPlan } from '@hardkas/tx-builder';
import { WalletUtxoApi } from './utxos.js';
import { UtxoControlStore } from './stores/utxo-control-store.js';
import { logger, metrics, tracer } from '@hardkas/observability';

metrics.register({
    name: "wallet_tx_generated_total",
    help: "Total tx generated by wallet",
    type: "counter"
});
metrics.register({
    name: "wallet_tx_submitted_total",
    help: "Total tx submitted by wallet",
    type: "counter"
});
metrics.register({
    name: "wallet_tx_failed_total",
    help: "Total tx failed by wallet",
    type: "counter"
});

export interface WalletToolkitOptions {
    storePath?: string;
    network?: "simnet" | "testnet" | "mainnet";
    provider?: WalletQueryProvider;
}

export class WalletToolkit {
    private walletManager: WalletManagerImpl;
    private addressManager: typeof AddressManager;
    private walletQuery: WalletQuery;

    private _utxosApi: WalletUtxoApi;

    private constructor(
        public readonly name: string,
        private readonly store: WalletStateStoreJson,
        private readonly options: WalletToolkitOptions
    ) {
        this.walletManager = new WalletManagerImpl();
        this.addressManager = AddressManager;
        
        const dummyProvider: WalletQueryProvider = {
            source: "dummy",
            async getBalances() { return {}; },
            async getUtxos() { return {}; },
            async getHistory() { return { items: [] }; }
        };

        this.walletQuery = new WalletQuery({ provider: options.provider || dummyProvider, network: options.network || "simnet" });
        
        const utxoControlPath = options.storePath 
            ? options.storePath.replace('.json', '-utxo-control.json')
            : 'default-utxo-control.json';
        const utxoStore = new UtxoControlStore(utxoControlPath);

        this._utxosApi = new WalletUtxoApi(
            async () => {
                const addr = await this.address();
                const res = await this.walletQuery.getUtxos([addr]);
                if (!res.ok) throw new Error(res.error || "Degraded query result");
                return res.utxos[addr] || [];
            },
            async () => this.address(),
            async (inputs: number, outputs: number) => BigInt(inputs * 1000 + outputs * 1000), // Dummy fee estimation
            utxoStore
        );
    }

    public static open(name: string, options: WalletToolkitOptions = {}): WalletToolkit {
        const store = new WalletStateStoreJson({ filePath: options.storePath || 'default.json' });
        return new WalletToolkit(name, store, options);
    }

    public async create(): Promise<void> {
        this.walletManager.create({ walletId: this.name });
    }

    public async address(): Promise<string> {
        // High level facade: gets receive address
        const seedRef = this.walletManager.getSeedRef(this.name);
        return this.addressManager.derive({ 
            seedRef, 
            accountIndex: 0,
            chain: 'receive', 
            addressIndex: 0, 
            network: this.options.network || 'simnet' 
        }).address;
    }

    public async balance(): Promise<bigint> {
        const addr = await this.address();
        return (await this.walletQuery.getBalance([addr])) as any;
    }

    public get utxos(): WalletUtxoApi {
        return this._utxosApi;
    }

    public async history(): Promise<any[]> {
        const addr = await this.address();
        return (await this.walletQuery.getHistory({ addresses: [addr] })) as any;
    }

    public async estimateFee(opts: { to: string; amount: bigint; feeRate?: bigint }): Promise<{ fee: bigint; totalOut: bigint; plan: any }> {
        const addr = await this.address();
        const availableUtxos = await this.utxos.list();
        
        const plan = buildPaymentPlan({
            fromAddress: addr,
            outputs: [{ address: opts.to, amountSompi: opts.amount }],
            availableUtxos: availableUtxos as any[],
            feeRateSompiPerMass: opts.feeRate || 1n,
            changeAddress: addr
        });

        return {
            fee: plan.estimatedFeeSompi,
            totalOut: opts.amount + plan.estimatedFeeSompi,
            plan
        };
    }

    public async planSend(opts: { to: string; amount: bigint; feeRate?: bigint }): Promise<any> {
        try {
            const { plan } = await this.estimateFee(opts);
            metrics.inc("wallet_tx_generated_total");
            logger.info("Wallet tx planned", { to: opts.to });
            return plan;
        } catch (e: any) {
            metrics.inc("wallet_tx_failed_total");
            logger.error("Wallet tx planning failed", { error: e.message });
            throw e;
        }
    }

    public async sendSimulated(opts: { to: string; amount: bigint; feeRate?: bigint }): Promise<string> {
        const span = tracer.start("wallet.send", { to: opts.to });
        try {
            const plan = await this.planSend(opts);
            const hashStr = `sim_tx_${Date.now()}_${plan.inputs.length}_${plan.outputs.length}`;
            for (const u of plan.inputs) {
                await this.utxos.freeze(`${u.outpoint.transactionId}:${u.outpoint.index}`, 'simulated_send');
            }
            metrics.inc("wallet_tx_submitted_total");
            logger.info("Wallet tx simulated successfully", { txid: hashStr });
            span.end({ txid: hashStr });
            return hashStr;
        } catch (e: any) {
            metrics.inc("wallet_tx_failed_total");
            logger.error("Wallet sendSimulated failed", { error: e.message });
            span.fail(e);
            throw e;
        }
    }
}
